name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Bicep CLI
        run: |
          az bicep install

      - name: Validate Bicep file
        run: |
          az bicep build --file <path-to-bicep-file>

      - name: Deploy Bicep file to Azure
        run: |
          az deployment group create --resource-group <resource-group-name> --template-file <path-to-bicep-file> --parameters <path-to-parameters-json-file>
