name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  APIM-DEV-BICEP:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Bicep CLI
        run: az bicep install
  
      - name: Validate Bicep file
        run: az bicep build --file bicep/dev-apim.bicep
      - name: Deploy Bicep file
        run: |
              az deployment group create \
                --resource-group APIMTesting \
                --template-file bicep/dev-apim.bicep \
                --parameters @bicep/parameters.json
